### ISSUE TITLE
block-indent option

### ISSUE THREAD

**Issue by tonyganch** [csscomb/csscomb.js#114]
I'm having hard times trying to understand how `block-indent` option works.
This is an example from our tests:

``` css
/* Before */
 a
{ color: red }  @media all { .input__control
{ color: #000;
}
}

/* After, block-indent: 4 */
a
{ color: red 
}
@media all {
    .input__control
    { color: #000;
    }
}
```

See that first space before `a` in "before" part? Why is it dead in "after"? Who killed it?

I thought that, ok, maybe `block-indent` takes a block (everything inside `{` and `}`) and indents it (i.e. adds 4 spaces for every line) and since `a` is kind of a root node, there should be no spaces before the selector, so we remove them.
Is it so?

Then there is a line break before `@media all`.
Why? Because it's a selector?

Then there are line breaks before all closing brackets `}`.
Are there line breaks after all opening brackets? No.
One line break after `{` before `.input__control` but no line breaks after `{` before `color`.
Why oh why?

Also, it's hard to see, but there is a trailing whitespace after `red` but, surprise surprise, no trailing whitespace after `@media all {`.
Why???

But that's not all folks.
The most interesting is this case:

``` css
/* Before */
 a
{ color: red }  @media all { .input__control
{ color: #000;
top: 0;
}
}
```

There is only one declaration added to the first case.
Can anyone guess the result code?

I was so naive to think it would be this:

``` css
/* After */
a
{ color: red 
}
@media all {
    .input__control
    { color: #000;
    top: 0;
    }
}
```

But in fact you get this:

``` css
/* After */
a
{ color: red 
}
@media all {
    .input__control
    { color: #000;
top: 0;
    }
}
```

So my question is: how does `block-indent` works?
Can someone explain it in words please?

I have a branch with a bit more readable tests here:
https://github.com/csscomb/csscomb.js/tree/tg/block-indent/test/block-indent
Feel free to use it.
