### ISSUE TITLE
Remove empty rulesets kills rules without declarations

### ISSUE THREAD

**Issue by tonyganch** [csscomb/csscomb.js#133]
Version 2.0, default `csscomb` config.

Input:

``` scss
@mixin mix-all {
    border: solid 1px #c00;
}
@mixin mix-top {
    border-top: none;
}

.parent {
    @include mix-all;
    @include mix-top;
}
```

Result:

``` scss
@mixin mix-all {
    border: solid 1px #c00;
}
@mixin mix-top {
    border-top: none;
}
```

The code is expected not to be changed at all.

If you add at least one declaration to `.parent` block, everything works fine.
