### ISSUE TITLE
Option: always-semicolon

### ISSUE THREAD

**Issue by mishanga** [csscomb/csscomb.js#14]
Default value — false (no changes will be made).
Available value: Boolean true — 1 space after colon (same as `after`)

Example:

``` javascript
"always-semicolon": true
```

Before:

``` css
a { color: red }
```

After:

``` css
a { color: red; }
```
