### ISSUE TITLE
New option: ensure parent reference in selectors for preprocessors

### ISSUE THREAD

**Issue by kizu** [csscomb/csscomb.js#140]
As we now have basic preprocessors support, we could start adding preprocessor-oriented options like this :)

All preprocessors allow us to omit the parent reference (`&`) at selectors. Some people like that, while some — don't.

It would nice to have an option to control this, so when there would be something like that:

``` scss
.foo {
  width: 10px;
  
  .bar {
    height: 10px;
  }
}
```

You could change it to this:

``` scss
.foo {
  width: 10px;
  
  & .bar {
    height: 10px;
  }
}
```

and vice versa.

The possible names for this option could be `mandatory-parent-reference`, `ensure-parent-referece` or something like that.
