### ISSUE TITLE
Extend sort-order, add option to sort specific mixins by name

### ISSUE THREAD

**Issue by denisborovikov** [csscomb/csscomb.js#143]
Example: 
```
{ "sort-order": [ [ "$variable" ], [ "$include" ],  [ "$include foo-mixin" ],[ "top", "padding" ] ,  [ "$include bar-mixin" ]] }
```

Some mixins are useful to place after all declarations at the bottom of the rule.

**Comment by dkeeghan** [comment]
I've found the use case like this:

```scss
.module {
    color: red;

    .child {
        color: blue;
    }

    @include bp(m) {
        color: yellow;

        .child {
            color: green;
        }
    }
}
```

Which is exported out as:

```scss
.module {
    color: red;

    @include bp(m) {
        color: yellow;

        .child {
            color: green;
        }
    }

    .child {
        color: blue;
    }
}
```

Which makes the child always blue and not green at the `m` breakpoint like I would expect.

Ideally I would love to be able to sort the selectors like:

property, @include (except bp), children, @include bp
