### ISSUE TITLE
Support for alphabetical property ordering

### ISSUE THREAD

**Issue by necolas** [csscomb/csscomb.js#158]
Couldn't see any way to config alphabetical sorting in the docs.

**Comment by powelski** [comment]
Any updates on this? I'd be glad to have this feature, as I'm using alphabetical order.

**Comment by tonyganch** [comment]
@powelski, https://github.com/csscomb/csscomb.js/blob/master/doc/options.md#sort-order-fallback
See the second example.

**Comment by powelski** [comment]
@tonyganch Thanks, it works! :smile:

**Comment by mscarchilli** [comment]
The alpha fall back works pretty good, but it doesn't sort everything in alpha from my tests in SCSS. Overall it's pretty good, just not for real use with SCSS just yet. Adding everything to the config file can be one hell of a tasks, as not all templates out there have all styles necessarily.

For example. This:

```scss
#foobar
{
  height: auto;
  left: 0;
  max-height : 100vh;

    top: 0;
  overflow: hidden;
  width: 100%;
position: absolute;
  z-index: 9999;

  polygon {
    transform-origin: center center;
    transition: all 3s ease-in-out;
    opacity: 0;

    fill: #fff;
    &.stop {
        opacity: 1 !important;       transform: translate(0, 0) !important;
    }
  }
}
```

Compiles to this:

```scss
#foobar {
  height: auto;
  left: 0;
  max-height: 100vh;
  top: 0;
  overflow: hidden;
  width: 100%;
  position: absolute;
  z-index: 9999;

  polygon {
    transform-origin: center center;
    transition: all 3s ease-in-out;
    opacity: 0;
    fill: #fff;
    &.stop {
      opacity: 1 !important;
      transform: translate(0, 0) !important;
    }
  }
}
```

Also it would be nice to add the line break before "&.stop"
