### ISSUE TITLE
Option: vendor-prefix-align

### ISSUE THREAD

**Issue by nataschachu** [csscomb/csscomb.js#17]
Default value — false (no changes will be made).

Available value: Boolean true — rules are indented by base rule name, values — by colon.

Example:

``` javascript
"vendor-prefix-align": true
```

Before:

``` css
a {
  -webkit-border-radius: 3px;
  -moz-border-radius: 3px;
  border-radius: 3px;
}
b {
  background: -webkit-gradient(linear, left top, right top, color-stop(0,rgba(255,255,255,0)), color-stop(20%, #fff));
  background: -moz-linear-gradient(left, rgba(255,255,255,0) 0, #fff 20%);
  background: -o-linear-gradient(left, rgba(255,255,255,0) 0, #fff 20%);
  background: -ms-linear-gradient(left, rgba(255,255,255,0) 0, #fff 20%);
  background: linear-gradient(to right, rgba(255,255,255,0) 0, #fff 20%);
}
```

After:

``` css
a {
  -webkit-border-radius: 3px;
     -moz-border-radius: 3px;
          border-radius: 3px;
}
b {
  background: -webkit-gradient(linear, left top, right top, color-stop(0,rgba(255,255,255,0)), color-stop(20%, #fff));
  background: -moz-linear-gradient(left, rgba(255,255,255,0) 0, #fff 20%);
  background:   -o-linear-gradient(left, rgba(255,255,255,0) 0, #fff 20%);
  background:  -ms-linear-gradient(left, rgba(255,255,255,0) 0, #fff 20%);
  background:      linear-gradient(to right, rgba(255,255,255,0) 0, #fff 20%);
}
```
