### ISSUE TITLE
Лишние переносы строк при "stick-brace": "\n"

### ISSUE THREAD

**Issue by cy6erskunk** [csscomb/csscomb.js#19]
``` css
.lol, .nyan,
.xxx
{
    width: 0;
}
```

превращается в

``` css
.lol
, .nyan
,

.xxx
{
    width: 0;
}
```
