### ISSUE TITLE
New option: Space after declaration

### ISSUE THREAD

**Issue by tonyganch** [csscomb/csscomb.js#197]
Example: `{ 'space-after-declaration': '\n  ' }`

``` scss
// Before:
a {
  top: 0; color: tomato; position: panda;
}

// After:
a {
  top: 0;
  color: tomato;
  position: panda;
}
```

Example: `{ 'space-after-declaration': 0 }`

``` scss
// Before:
a {
  top: 0;
  color: tomato;
  position: panda;
}

// After:
a {
  top: 0;color: tomato;position: panda;}
```

Conflicting options:
- `block-indent` should be more important than `space-after-declaration`
- `space-before-closing-brace` should be more important than both `block-indent` and `space-after-declaration`
