### ISSUE TITLE
New option: Root indent

### ISSUE THREAD

**Issue by tonyganch** [csscomb/csscomb.js#198]
Maybe the option should be named just `indent` instead.

Example: `{ 'root-indent': 4 }`
```scss
// Before:
a,
  b,
    c
{
    color: tomato;
    top: 0;
}

// After:
    a
    {
    color: tomato;
    top: 0;
    }
```

Example: `{ 'root-indent': '' }`
```scss
// Before:
a,
  b,
    c
{
    color: tomato;
    top: 0;
}

// After:
a
{
color: tomato;
top: 0;
}
```

Conflicting options:

- If `block-indent` is not set, `root-indent` should set indent for all lines regardless of indent level (see examples above).    
If `block-indent` is set, the result indent should be sum of `block-indent` and `root-indent`.    
Example: `{ 'root-indent': 4, 'block-indent': 4 }`
```scss
// Before:
a,
  b,
    c
{
    color: tomato;
    top: 0;
}

// After:
    a
    {
        color: tomato;
        top: 0;
    }
```
