### ISSUE TITLE
Option: rule-indent

### ISSUE THREAD

**Issue by mishanga** [csscomb/csscomb.js#2]
Default value — false (no changes will be made).

Available (valid) values:
1) Boolean true — 4 spaces
2) Number n — {n} spaces
3) String `^[ \t]+$`

Examples:

``` javascript
"rule-indent": true
"rule-indent": 2
"rule-indent": "\t"
```

Results:

``` css
/* true */
a {
    color: red;
}

/* 2 */
a {
  color: red;
}

/* \t */
a {
        color: red;
}
```
