### ISSUE TITLE
Less & auto semi colon insertion bug

### ISSUE THREAD

**Issue by dmmalam** [csscomb/csscomb.js#201]
The following LESS 

``` less
#a {

  #b {
      text-align: right;
  }

  #d {
    .e {
      text-align: center;
    }
  }
}

```

is erroneously  converted to 

```
#a {

  #b {
      text-align: right;
  }

  #d; {
    .e; {
      text-align: center;
    }
  }
}
```

Notice the extra semi-colon on the #d and .e selector

with config

``` json
{
  "always-semicolon": true,
  "color-case": "upper",
  "color-shorthand": false,
  "combinator-space": [1, 1],
  "element-case": "lower",
  "eof-newline": true,
  "leading-zero": true,
  "quotes": "single",
  "remove-empty-rulesets": false,
  "stick-brace": 1,
  "strip-spaces": true,
  "unitless-zero": true,
  "vendor-prefix-align": true
}
```
