### ISSUE TITLE
New option: rule-delimiter

### ISSUE THREAD

**Issue by tonyganch** [csscomb/csscomb.js#210]
Moved from #209:

I guess we should add an option like `rule-delimiter` which will set spaces between rulesets and media queries (this has been already discussed in #92).
It seems to me that this option should be more important than `space-after-declaration` (see #197).
So we can have, for example: `{ 'space-after-declaration': 1, 'rule-delimiter': '\n\n' }`

``` scss
// Before
a {
    color: tomato;
    top: 0;
    panda {
        position: happy;
    }
    raccoon {
        a: b;
    }
    foo: bar;
}
div {
    border: none;
}

// After
a {
    color: tomato; top: 0;

    panda {
        position: happy;
    }

    raccoon {
        a: b;
    }

    foo: bar;
}

div {
    border: none;
}
```
##
