### ISSUE TITLE
Option: block-indent

### ISSUE THREAD

**Issue by mishanga** [csscomb/csscomb.js#22]
Default value — false (no changes will be made).

Available (valid) values:
1) Boolean true — 4 spaces
2) Number n — {n} spaces
3) String `^[ \t]+$`

Examples:

``` javascript
"block-indent": true
"block-indent": 2
"block-indent": "\t"
```

Before:

``` css
/* true */
     a { color: red; }
i {
  color: red;
   }
  @media all and (min-width:0px) {
    b { font: 0/0 a; }
  }
```

After:

``` css
/* true */
a { color: red; }
i {
  color: red;
}
@media all and (min-width:0px) {
    b { font: 0/0 a; }
}
```
