### ISSUE TITLE
Problem with nested less rules

### ISSUE THREAD

**Issue by fidel-karsto** [csscomb/csscomb.js#228]
This is an example of a nested less definition:

``` css
body .quick-paging {
    width: 170px;
    height: 30px;

    .btn-prev {
        padding: 8px 10px 7px;
    }
    .btn-prev span.icon {
        bottom: 2px;
    }
    .label {
        background: none transparent;
    }
    .btn-next {
        margin-left: 0;
    }
    .btn-prev.disabled {
        visibility: visible;
    }
    .btn-prev:hover {
        background-color: yellow;
    }
    .btn-prev:active {
        background-color: red;
    }
}
```

And this is the result after csscomb run

``` css
body .quick-paging
{
    width: 170px;
    height: 30px;

    .btn-prev 
    .btn-prev 
    .label 
    .btn-next 
    .btn-prev.disabled 
    .btn-prev:
    .btn-prev:;{
    padding: 8px 10px 7px;
}span.icon
{
    bottom: 2px;
}{
    background: none transparent;
}{
    margin-left: 0;
}{
    visibility: visible;
}hover
{
    background-color: yellow;
}active
{
    background-color: red;
}
}
```

As you can see the result is an invalid less/css file because of those misplaced colons (after .btn-prev). Also the pseudo elements :hover and :active are misplaced.
I first encountered the problem using grunt-csscomb, but I verified the behaviour by cloning the standalone version, altering nested-rule.less and running:

``` shell
./bin/csscomb -v test/core/less/nested-rule.less
```

Any help would be apreciated. :)
