### ISSUE TITLE
New option: remove-comments

### ISSUE THREAD

**Issue by tonyganch** [csscomb/csscomb.js#235]
The option should work like `remove-empty-rulesets` and help make css cleaner.

Example: `{ 'remove-comments': true }`

```scss
// Before:
a {
  /* comment */
  color: panda; // comment
  top: 0; /* comment */ left: 0
}

// After:
a {
  
  color: panda; 
  top: 0;  left: 0
}
```
