### ISSUE TITLE
v3.0: not all properties on new line

### ISSUE THREAD

**Issue by ghost** [csscomb/csscomb.js#239]
Hello,

Formatting a compressed source not all properties will start on a new line

before

``` css
html{color:#444;font-family:proxima-nova;font-size:62.5%;font-weight:300;line-height:1.5}
.sub-menu a{border-right:1px solid #eee;border-bottom:1px solid #eee;border-left:1px solid #eee;color:#999;background-color:#fff}
.site{left:0!important;-webkit-transition:-webkit-transform 500ms ease;-moz-transition:-moz-transform 500ms ease;-o-transition:-o-transform 500ms ease;transition:transform 500ms ease;-webkit-transform:translate3d(0,0,0);-moz-transform:translate3d(0,0,0);-ms-transform:translate3d(0,0,0);-o-transform:translate3d(0,0,0);transform:translate3d(0,0,0)}
.toggled .site{left:70%;-webkit-transform:translate3d(70%,0,0) scale3d(1,1,1);-moz-transform:translate3d(70%,0,0) scale3d(1,1,1);-ms-transform:translate3d(70%,0,0) scale3d(1,1,1);-o-transform:translate3d(70%,0,0) scale3d(1,1,1);transform:translate3d(70%,0,0) scale3d(1,1,1)}
```

after

``` css
html {
    color: #444;
    font-family: proxima-nova;
    font-size: 62.5%;
    font-weight: 300;line-height: 1.5;
}
.sub-menu a {
    border-right: 1px solid #eee;
    border-bottom: 1px solid #eee;
    border-left: 1px solid #eee;
    color: #999;background-color: #fff;
}
.site {
    left: 0!important;
    -webkit-transition: -webkit-transform 500ms ease;
    -moz-transition: -moz-transform 500ms ease;
    -o-transition: -o-transform 500ms ease;
    transition: transform 500ms ease;
    -webkit-transform: translate3d(0,0,0);
    -moz-transform: translate3d(0,0,0);
    -ms-transform: translate3d(0,0,0);-o-transform: translate3d(0,0,0);transform: translate3d(0,0,0);
}
.toggled .site {
    left: 70%;
    -webkit-transform: translate3d(70%,0,0) scale3d(1,1,1);
    -moz-transform: translate3d(70%,0,0) scale3d(1,1,1);
    -ms-transform: translate3d(70%,0,0) scale3d(1,1,1);
    -o-transform: translate3d(70%,0,0) scale3d(1,1,1);transform: translate3d(70%,0,0) scale3d(1,1,1);
}
```

my .csscomb.json

``` json
{
  "exclude": [
    ".git/**",
    "node_modules/**"
   ],
  "always-semicolon": true,
  "block-indent": "\t",
  "color-case": "lower",
  "color-shorthand": true,
  "element-case": "lower",
  "eof-newline": true,
  "leading-zero": false,
  "quotes": "double",
  "remove-empty-rulesets": true,
  "sort-order-fallback": "abc",
  "space-after-colon": 1,
  "space-after-combinator": 1,
  "space-after-declaration": "\n",
  "space-after-opening-brace": "\n",
  "space-after-selector-delimiter": "\n",
  "space-before-closing-brace": "\n",
  "space-before-colon": 0,
  "space-before-combinator": 1,
  "space-before-opening-brace": 1,
  "space-before-selector-delimiter": 0,
  "strip-spaces": true,
  "unitless-zero": true,
  "vendor-prefix-align": false,
  "sort-order": [
    "$variable",
    "$include",

    "display",
    "visibility",
    ...
  ]
}
```

Could someone perhaps tell what I'm overlooking here?
