### ISSUE TITLE
space-after-declaration vs comments

### ISSUE THREAD

**Issue by tonyganch** [csscomb/csscomb.js#251]
@mishanga @kizu, I can really use your advice here.

Take this code as an example:

``` scss
a {
  color: tomato;      /* comment */
  position: fixed;
  /* comment */
  top: 0;
  left: 0;

  &:hover {
    color: black;     // comment
    top: 100%;
  }
}
```

What should be the result after processing this code with settings:
1. `'space-after-declaration': ' '` and
2. `'space-after-declaration': '\n'`?

Related issue: #232
