### ISSUE TITLE
Less css selector's parrent

### ISSUE THREAD

**Issue by red-led** [csscomb/csscomb.js#254]
Source less code:

``` css
.Foo
{
    display: block;
    &_Bar
    {
        display: block;
    }
}
```

& represents the current selector parent, so result css selector is '.Foo_Bar'. But CSScomb parses _Bar as tag name and makes it lowercase "&_bar".
##

**Comment by francoismassart** [comment]
@tonyganch I'd like to try to work on this issue and (if I succeed) submit a PR...
Can you confirm that nobody did look into this specific issue?

**Comment by francoismassart** [comment]
The bug also occurs in SCSS:

```scss
// Before CSS Comb
.Foo
{
    display: block;
    &_Bar
    {
        display: block;
    }
}

// Expected after applying CSS Comb
.Foo 
{
    display: block;
    &_Bar 
    {
        display: block;
    }
}

// After CSS Comb we get &_bar instead of &_Bar
.Foo 
{
    display: block;
    &_bar 
    {
        display: block;
    }
}
```
Personnaly, I aim to use only lowercase in my selectors but I'll try to find out what is wrong...
