### ISSUE TITLE
Less css media variables

### ISSUE THREAD

**Issue by red-led** [csscomb/csscomb.js#255]
``` css
@widthSmall:    ~"(max-width: 1300px)";

.Foo {
  @media @widthSmall {
      width:    400px;
  }
}
```

Throws error:

```
stack:  Error: Parsing error at test.less: Please check the validity of the CSS block starting from the line #1
    at cssToAST (/usr/lib/node_modules/csscomb/lib/csscomb.js:464:19)
    at processString (/usr/lib/node_modules/csscomb/lib/csscomb.js:351:20)
    at /usr/lib/node_modules/csscomb/lib/csscomb.js:323:39
    at Array.0 (/usr/lib/node_modules/csscomb/node_modules/vow/lib/vow.js:555:56)
    at Object.callFns [as _onImmediate] (/usr/lib/node_modules/csscomb/node_modules/vow/lib/vow.js:1148:35)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```
##
