### ISSUE TITLE
Specifying "sort-order" reset "space-before-opening-brace"

### ISSUE THREAD

**Issue by Romainpetit** [csscomb/csscomb.js#262]
When using "sort-order", a \n is automatically applied before opening brace. I would like the brace to stay right after the declaration without space.
##

**Comment by ausminternet** [comment]
Same Problem here.

This:
```css
h1 { padding: 2px;
  font-size: 12px;

  font-weight: bold;
}

h2 {
  font-size: 12px;
  padding: 2px;

  font-weight: bold; }
```
becomes:
```css
h1
{
    font-size: 12px;
    font-weight: bold;

    padding: 2px;
}

h2
{
    font-size: 12px;
    font-weight: bold;

    padding: 2px;
}
```
with this config: (sort-order is default)
```json
{
        "remove-empty-rulesets": true,
        "always-semicolon": true,
        "color-case": "lower",
        "block-indent": "\t",
        "color-shorthand": false,
        "element-case": "lower",
        "eof-newline": true,
        "leading-zero": false,
        "quotes": "single",
        "sort-order-fallback": "abc",
        "space-before-colon": "",
        "space-after-colon": " ",
        "space-before-combinator": " ",
        "space-after-combinator": " ",
        "space-between-declarations": "\n",
        "space-before-opening-brace": " ",
        "space-after-opening-brace": "\n",
        "space-after-selector-delimiter": "\n",
        "space-before-selector-delimiter": "",
        "space-before-closing-brace": "\n",
        "strip-spaces": true,
        "tab-size": true,
        "unitless-zero": true,
        "vendor-prefix-align": true
    }
```
