### ISSUE TITLE
LESS: Mixins on top

### ISSUE THREAD

**Issue by mrmlnc** [csscomb/csscomb.js#274]
Before the update was:

``` CSS
header[role="banner"] {
  .box-shadow(0 2px 5px 0 rgba(0, 0, 0, .26));
  position: relative;

  .header-brand {
    height: @header-height;
  }
}
```

Now:

``` CSS
header[role="banner"] {
  position: relative;

  .box-shadow(0 2px 5px 0 rgba(0, 0, 0, .26));
  .header-brand {
    height: @header-height;
  }
}
```

Can I fix this?

**Or even better, to do so:**

``` CSS
header[role="banner"] {
  position: relative;
  .box-shadow(0 2px 5px 0 rgba(0, 0, 0, .26));

  .header-brand {
    height: @header-height;
  }
}
```

Thanks for the reply!
