### ISSUE TITLE
`space-before-colon` breaks :hover selector for Less file

### ISSUE THREAD

**Issue by svartalf** [csscomb/csscomb.js#280]
Enabled `space-before-colon` breaks less nested selector, note the space between `a:` and `hover`:
```less
/* before */

li {
	a, a:link, a:visited, a:hover {
		font-weight: normal;
		text-decoration: underline;
	}
	a:hover {
		text-decoration: none;
	}
}

/* after */

li {
    a: hover {
        text-decoration: none;
    }
        a, a:link, a:visited, a:hover {
            font-weight: normal;

            text-decoration: underline;
        }
}
```

csscomb version: 3.0.0
