### ISSUE TITLE
Option to add (or leave) a space after a property

### ISSUE THREAD

**Issue by sergiofontes** [csscomb/csscomb.js#282]
In previous version, it allowed me to leave the breaklines after a property is closed. I should be able to leave my code like this:

``` css
h1 {
color: blue;
margin: 20px 0;
}

p {
color: black;
margin: 20px 0 0;
}
```

Not be forced to:

``` css
h1 {
color: blue;
margin: 20px 0;
}
p {
color: black;
margin: 20px 0 0;
}
```
