### ISSUE TITLE
Error on empty rules

### ISSUE THREAD

**Issue by hudochenkov** [csscomb/csscomb.js#289]
CSScomb throw an error if SCSS has empty rules.

```
$ ./node_modules/.bin/csscomb test.scss
stack:  TypeError: Cannot read property '0' of undefined
    at module.exports.process (/Users/aleks/asdf/node_modules/csscomb/lib/options/space-after-opening-brace.js:25:20)
    at /Users/aleks/asdf/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:206:21
    at Array.forEach (native)
    at processNode (/Users/aleks/asdf/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
    at /Users/aleks/asdf/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:211:13
    at Array.forEach (native)
    at processNode (/Users/aleks/asdf/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
    at /Users/aleks/asdf/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:211:13
    at Array.forEach (native)
    at processNode (/Users/aleks/asdf/node_modules/csscomb/node_modules/csscomb-core/lib/core.js:202:14)
```

Example code (test.scss):

```scss
.account-login {
	&__reward {
		display: inline-block;
		vertical-align: middle;
		width: 27px;
		height: 27px;
		margin-left: 2px;
		background-image: url("img/dollar.png");
		text-indent: -9999px;
	}
	&__create-account {}
	&__create-account-variant {
		text-align: center;
		padding: 30px 0;
		&:first-child {
			width: 50%;
			float: left;
		}
	}
}
```

Issue related to #281.
