### ISSUE TITLE
Sort order fallback: Add `yandex`, `zen` and `csscomb`

### ISSUE THREAD

**Issue by tonyganch** [csscomb/csscomb.js#299]
From discussion with @matmuchrapna:

Allow using sort orders from predefined configs as `sort-order-fallback` option.
For example:

``` json
{
  "always-semicolon": true,
  "sort-order": ["color", "..."],
  "sort-order-fallback": "yandex"
}
```

``` scss
// Before
a {
  left: 0;
  color: 0;
  top: 0;
}

// Before
a {
  color: 0;
  top: 0;
  left: 0;
}
```
##
