### ISSUE TITLE
Option: stick-brace

### ISSUE THREAD

**Issue by mishanga** [csscomb/csscomb.js#3]
Default value — false (no changes will be made).

Available (valid) values:
1) Boolean true — 1 space
2) String `\s+` — `selector%space%{`

Examples:

``` javascript
"stick-brace": true
"stick-brace": "\n"
```

Results:

``` css
/* true */
a {
    color: red;
}

/* \n */
a
{
    color: red;
}
```
