### ISSUE TITLE
SCSS: // Single line comment error

### ISSUE THREAD

**Issue by francoismassart** [csscomb/csscomb.js#303]
When I try the online parser with this Scss code:

``` scss
// Hello
.world:after {
  content: "does not work...";
}
```

I get this error:

```
Please check the validity of the block starting from line #1

1*| // Hello
2 | .world:after {
3 |   content: "does not work...";

Gonzales PE version: 3.0.0-10
CSScomb Core version: 2.0.2
```

Any idea on how to fix this ?
