### ISSUE TITLE
New option: minimum-space-after-colon

### ISSUE THREAD

**Issue by francoismassart** [csscomb/csscomb.js#307]
The existing option "space-after-colon" is nice most of the time but sometimes I like to use extra whitespace(s) in order to align values of different properties...

Here is an example:

``` scss
// Before CSS Comb
$size: 50px;
.selector {
  width:  $size;
  height: $size;
}
```

See how I used 2 spaces after "width" ? This is usefull to increase readability!
Now, when csscomb is applied, it either removes all spaces after ":" or it adds the same number of spaces... 

``` scss
// After CSS Comb
$size: 50px;
.selector {
  width: $size;
  height: $size;
}
```

Maybe, it would be useful to add a new config option that could say 
"I want at least 1 space but if there are more, let it be."

What do you think about this (minor) improvement ?
