### ISSUE TITLE
space-after-colon hates pseudo class selectors in nested LESS

### ISSUE THREAD

**Issue by kaleb** [csscomb/csscomb.js#309]
Input:

```
.broken {          
    a:hover {              
        color: #fff;
    }              
}                  
```

After:

```
.broken             
{
    a: hover        
    {               
        color: #fff;
    }               
}                   
```

Look at the space after `a:`.
##

**Comment by sadsat** [comment]
I can confirm this for csscomb-grunt.

A workaround seems to be the usage of another nesting level:

```
.module {
    article {
        &:last-child {
           ... 
        }
    }
}
```

**Comment by maxfenton** [comment]
+1

**Comment by SpencerCarstens** [comment]
+1

Found this the hard way today.

**Comment by ganchan** [comment]
I've noticed that this do not happen when you use this syntax
```less
li
{
  &:last-child
  {
  // some styles
  }
}

**Comment by Kepro** [comment]
easy way to fix it just set "space-after-colon": 0,

**Comment by maxfenton** [comment]
`easy way to fix it just set "space-after-colon": 0,` — that's actually a good help towards seeing where the problem is, @kepro 

Thanks.

**Comment by Buzut** [comment]
Is this fixed? csscomb 3.1.7 with gulp-csscomb 3.0.8 here and I still have the bug. Culprit code:

```css
#menu {
    padding: 0;
    margin: 0;

    .navlinks {
        margin-top: 5px;

        // HERE (adds a space after "a:")
        a:last-child {
            padding-left: 14px;
            margin-left: 12px;
            content: "";
            border-left: 1px solid #273041;
        }
    }

    .menuicons {
        margin-top: 8px;

        .icon {
            float: right;
            margin-left: 10px;
            cursor: pointer;
        }
    }
}
```
