### ISSUE TITLE
Option Request: space-between-nested-blocks

### ISSUE THREAD

**Issue by PD-WebTools** [csscomb/csscomb.js#317]
I would like to suggest an option, space-between-nested-blocks.  For my needs, I'd just like to make sure there is a line between my current rules and a nested selector.  Example:

### Example Source

```
.foo {
  color: black;
  .bar {
    color: gray;
  }
}
```

### space-between-nested-blocks = true

```
.foo {
  color: black;
  
  .bar {
    color: gray;
  }
}
```

**Comment by hudochenkov** [comment]
@tonyganch, what are you think about this [commit](https://github.com/jeroenransijn/csscomb.js/commit/dc3afb64abbd91924819a25f2563c6c230214bf7)? It looks like solution for this. This issue not exactly related to rule-delimeter and you pointed on this in [comment](https://github.com/csscomb/csscomb.js/issues/210#issuecomment-52078049).

I've also need this feature and want to try make PR.

**Comment by tonyganch** [comment]
@hudochenkov, can you show a few examples (before and after) to illustrate what you want to achieve?

**Comment by tonyganch** [comment]
@hudochenkov, you want to sort rulesets too? Based on selectors?

**Comment by hudochenkov** [comment]
I want to visual separate block's properties, includes, extends and it's children. As I understand, now block's children not participating in sort-order. So it glued with no empty lines with all sort-order effected nodes. If we can identify all block's children as one entity, we can put them in sort-order. Previous implementation of `$include` works similar way: it gather all `@include` and `@​extend` in order presented in source file.

Example config:

```json
{ "sort-order": [

["position", "top", "left", "margin", "padding", "padding-right", "content"],
["$include desk", "$include palm"],
["$nested-blocks"]

]}
```

Before:

```scss
.panel {
	position: absolute;
	top: 0;
	left: 0;
	&__inner {
		padding: 0 8px 0 20px;
		&:before {
			content: "";
		}
	}
	&__close {
		display: block;
	}
}
```

After (added two empty lines):

```scss
.panel {
	position: absolute;
	top: 0;
	left: 0;

	&__inner {
		padding: 0 8px 0 20px;

		&:before {
			content: "";
		}
	}
	&__close {
		display: block;
	}
}
```

<hr>

Before:

```scss
.panel {
	position: absolute;
	top: 0;
	left: 0;

	@include palm {
		position: relative;
	}

	&__inner {
		padding: 0 8px 0 20px;

		@include desk {
			margin: 0 3.5%;
		}
		@include palm {
			padding-right: 20px;
		}
	}
	&__close {
		display: block;
	}
}
```

After (added one empty line):

```scss
.panel {
	position: absolute;
	top: 0;
	left: 0;

	@include palm {
		position: relative;
	}

	&__inner {
		padding: 0 8px 0 20px;

		@include desk {
			margin: 0 3.5%;
		}
		@include palm {
			padding-right: 20px;
		}
	}
	&__close {
		display: block;
	}
}
```
