### ISSUE TITLE
Nested braces-support

### ISSUE THREAD

**Issue by einfallstoll** [csscomb/csscomb.js#327]
I figured out, that CSSComb doesn't like nested braces.

``` less
.foo {
    width: calc((2 * @bar));
}
```

The CLI prints the following stack:

```
stack:  assets/less/test.less
Please check the validity of the block starting from line #3

1 | .foo {
2 |     width: calc((2 * @bar));
3*| }

Gonzales PE version: 3.0.0-10
CSScomb Core version: 2.0.3
```

It's useful to make further calculations.
##
