### ISSUE TITLE
Ignore certain parts of files

### ISSUE THREAD

**Issue by jblandry** [csscomb/csscomb.js#328]
I would appreciate if there was a way for scss logical code not to be processed.

``` scss

.blocks {
    font-weight:bold;

    // from here
    @each $id, $data in $section-colorscheme {
        $body:  map-get($data, body);
        $class: map-get($data, class);
        $base:  map-get($data, base);
        $lite:  map-get($data, lite);
        $dark:  map-get($data, dark);

        body#{$body} & { background-color: $lite; }
        &#{$class}     { color: $base; background-color: $dark; }

        @if $id == beta {
            &::before { content: 'BBB'; }
        }
    }
    // to here
}
```

I figure it's complicated so I was wondering if there could be ignore comment command:

``` scss

.blocks {
    font-weight:bold;

    // csscomb:ignore:start
    @each $id, $data in $section-colorscheme {
        $body:  map-get($data, body);
        $class: map-get($data, class);
        $base:  map-get($data, base);
        $lite:  map-get($data, lite);
        $dark:  map-get($data, dark);

        body#{$body} & { background-color: $lite; }
        &#{$class}     { color: $base; background-color: $dark; }

        @if $id == beta {
            &::before { content: 'BBB'; }
        }
    }
    // csscomb:ignore:end
}
```

Thanks in advance
##
