### ISSUE TITLE
Alphabetical ordering should ignore property values

### ISSUE THREAD

**Issue by necolas** [csscomb/csscomb.js#330]
The tool rewrites this:

``` css
button {
  outline: 1px dotted;
  outline: 5px auto -webkit-focus-ring-color;
}
```

to this:

``` css
button {
  outline: 5px auto -webkit-focus-ring-color;
  outline: 1px dotted;
}
```

which changes the intended rendering.

I don't think it should rewrite or complain (in lint mode) about multiple declarations of the same property with different values.
##

**Comment by alfredbez** [comment]
Same issue here

CSS:
```css
em {
    width: fit-content;
    width: auto;
}
```

sometimes the result looks like this:
```css
em {
    width: fit-content;
    width: auto;
}
```

and sometimes like this:
```css
em {
    width: auto;
    width: fit-content;
}
```

.csscomb.json:
```javascript
{
    "remove-empty-rulesets": true,
    "always-semicolon": true,
    "color-case": "lower",
    "block-indent": 2,
    "color-shorthand": false,
    "element-case": "lower",
    "eof-newline": true,
    "leading-zero": false,
    "quotes": "single",
    "sort-order": [
                    [ "$variable" ],
                    [ "$include" ],
                    [ "top", "padding" ]
                  ],
    "sort-order-fallback": "abc",
    "space-before-colon": "",
    "space-after-colon": " ",
    "space-before-combinator": " ",
    "space-after-combinator": " ",
    "space-between-declarations": "\n",
    "space-before-opening-brace": "\n",
    "space-after-opening-brace": "\n",
    "space-after-selector-delimiter": "\n",
    "space-before-selector-delimiter": "",
    "space-before-closing-brace": "\n",
    "strip-spaces": true,
    "tab-size": true,
    "unitless-zero": true,
    "vendor-prefix-align": true
}
```

**Comment by dovyden** [comment]
see also #338 #366

**Comment by haschek** [comment]
Looks like the alphabetical sort fallback inverts the relative order of same properties. This is not happen if the property sort order is configured manually.

Config:

```json
{
    "sort-order": [ [ "margin-left" ] ],
    "sort-order-fallback": "abc"
}
```

Input:

```css
.test-sorting-config {
    margin-left: 1%;
    margin-left: 4px;
    margin-left: 1vw;
    margin-left: 2%;
    margin-left: 1vh;
}

.test-sorting-fallback {
    margin-right: 1vw;
    margin-right: 1%;
    margin-right: 3em;
    margin-right: 1vw;
    margin-right: 2%;
}
```

Output:

```css
.test-sorting-config {
  margin-left: 1%;
  margin-left: 4px;
  margin-left: 1vw;
  margin-left: 2%;
  margin-left: 1vh;
}

.test-sorting-fallback {
  margin-right: 2%;
  margin-right: 1vw;
  margin-right: 3em;
  margin-right: 1%;
  margin-right: 1vw;
}
```

While the order of ``margin-left`` is not changed, sorting of ``margin-right`` is now reverse. I've tested with csscom 3.1.7.
