### ISSUE TITLE
sass variable error

### ISSUE THREAD

**Issue by solome** [csscomb/csscomb.js#331]
for example:
```css
@mixin transition-slow()
{
      $transition-slow: color .7s ease-out;
    -webkit-transition: $transition-slow;
       -moz-transition: $transition-slow;
         -ms-transition: $transition-slow;
            -o-transition: $transition-slow;
}
```
the result is:
```css
@mixin transition-slow()
{
    -webkit-transition: $transition-slow;
       -moz-transition: $transition-slow;
         -ms-transition: $transition-slow;
            -o-transition: $transition-slow;

     $transition-slow: color .7s ease-out;
}
```
