### ISSUE TITLE
Incompatibility prefix -o- and property opacity

### ISSUE THREAD

**Issue by tenorok** [csscomb/csscomb.js#342]
Hello, looks like I found a bug.

I have this selector:

``` css
.selector
{
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
         -o-user-select: none;
            user-select: none;
    opacity: .1;
}
```

After running `csscomb` this selector becomes as below:

``` css
.selector
{
    -webkit-user-select: none;
       -moz-user-select: none;
        -ms-user-select: none;
            user-select: none;

    opacity: .1;

         -o-user-select: none;
}
```
