### ISSUE TITLE
Converting quotes breaks escape sequences on "content" property

### ISSUE THREAD

**Issue by joaocunha** [csscomb/csscomb.js#352]
Using Sublime Text plugin, but I assume it's a lib parsing issue.

```css
.foo {
  content: "\\";
}
```

Is comb'ed to:
```css
.foo {
  content: '\';
}
```

It should keep the double backslash.

**Comment by joaocunha** [comment]
It breaks the `quotes` attribute, too:

Source:
```css
.foo {
  quotes: " ";
}
```

Becomes:
```css
.foo {
  quotes: '' '';
```
