### ISSUE TITLE
"Merging blocks with identical properties" behaving awkwardly

### ISSUE THREAD

**Issue by joaocunha** [csscomb/csscomb.js#354]
> CSSO 1.3.11
> node v0.10.36

I don't know exactly what is going on, so I couldn't name the issue properly.

This snippet:
```css
.foo {
  color: green;
}
.bar {
  color: green;
}
div, section, span, table {
  background: green;
  color: red;
}
table, td, th {
  color: red;
}
```

...provides this output (which is expected):
```css
.foo,.bar{color:green}div,section,span,table,td,th{color:red}
```

But if I add a property, it doesn't merge `.foo` and `.bar` anymore:
```css
.foo {
  color: green;
}
.bar {
  color: green;
}
div, section, span, table {
  background: green; /* adding a property here breaks the merging */
  color: red;
}
table, td, th {
  color: red;
}
```

...but if I remove the `div` selector, it works again:
```css
.foo {
  color: green;
}
.bar {
  color: green;
}
/* div */ section, span, table {
  background: green; /* the attribute is still here, but it works now */
  color: red;
}
table, td, th {
  color: red;
}
```

Sorry for the lack of info, but this is quite `wtf`.
