### ISSUE TITLE
TypeError: Cannot call method 'is' of undefined, v3.1.3

### ISSUE THREAD

**Issue by belyanskii** [csscomb/csscomb.js#386]
Guys! We have a problems with CSS rules that have comment's like this:
```css
/* & */
.my-class
{
    color: red;
}
```

Look at **&**, after that comment CSSComb will crash with error in title.

**Comment by tonyganch** [comment]
Those four lines are processed fine in 3.1.3. I need following things in order to help you:
(1) full error stack;
(2) the smallest piece of code that fails so i can write a test;
(3) syntax of the file (css/scss).

**Comment by belyanskii** [comment]
@tonyganch hi!
Hm, let's try online!
Go to the http://csscomb.com/online, paste my example and try to "Comb it" :)

Or, offline:
 - take csscomb.js v3.1.3
 - create .css file with my example
 - try to comb

P.S. - i have another example!

```css
@media all and (min-width:0)
{
    /* & */
    .class
    {
        color: red;
    }
}
```
