### ISSUE TITLE
Broken CLI in dev branch

### ISSUE THREAD

**Issue by hudochenkov** [csscomb/csscomb.js#399]
CLI was broke with latests commits in `dev`.

Before `include-specified.scss`:

```scss
.block {
    color: black;

    @extend .hey;
    @extend %ho;

    @include media("lap") {
        color: green;
    }
    @include media("palm") {
        color: red;
    }
    @include last;
    @include hide-text;
}
```

After:

```
[object Promise]
```

`.csscomb.js`:

```json
{ "sort-order": [

["$extend", "color"]

]}
```

**Comment by tonyganch** [comment]
Should be ok now. Though I've made it as a hotfix and have not added any tests yet :speak_no_evil: 
Please let me know if the problem remains.

**Comment by hudochenkov** [comment]
CLI is working, but result it very broken. Before and config as in first message. After:

```scss
.block
{
    color: black;

    @extend .hey;
    @extend %ho;
    @include media('lap')
    {
        color: green;
    }@include media('palm')
    {
        color: red;
    }@include last;
    @include hide-text;
    
    
}

```
