### ISSUE TITLE
Option: colon-space

### ISSUE THREAD

**Issue by mishanga** [csscomb/csscomb.js#4]
Default value — false (no changes will be made).

Available (valid) values:
1) Boolean true — 1 space after colon (same as `after`)
2) String `before|after|both` — `color%a%:%b%`

Examples:

``` javascript
"colon-space": true
"colon-space": "both"
```

Results:

``` css
/* true */
a {
    color: red;
}

/* both */
a {
    color : red;
}
```
