### ISSUE TITLE
Indents for multiple backgrounds

### ISSUE THREAD

**Issue by in-in** [csscomb/csscomb.js#406]
Is it possible save indents for multiple backgrounds and also save each url() from new line?

``` scss
// Before:
body {
  background-image: 
    url(img/background1.png),
    url(img/background2.png);
}

// After:
body {
  background-image: url(img/background1.png),
  url(img/background2.png);
}
```
##
