### ISSUE TITLE
Error when trying to format nested selectors that contain `:first-of-type`

### ISSUE THREAD

**Issue by royriojas** [csscomb/csscomb.js#409]
Given the following input 

```less
.some-selector {
  button:first-of-type {
    color: red;
  }
  p:first-of-type {
    color: red;
  }  
}

```

cssComb produces 

```less
.some-selector {
  button: first-of-type {
    color: red;
  }
  p: first-of-type {
    color: red;
  }  
}
```
which is invalid.

For now a workaround is to do:

```less
.some-selector {
  button{
    &:first-of-type {
      color: red;
    }
  }
  p {
    &:first-of-type {
      color: red;
    }
  }  
}
```

Which is formatted as expected without errors
