### ISSUE TITLE
Option to wrap selectors within a fixed column width

### ISSUE THREAD

**Issue by jawshooah** [csscomb/csscomb.js#410]
It would be nice to have the option to wrap selectors to remain within a set column width, rather than only having a space or newline between each.

Refs StylishThemes/GitHub-Dark#239

\cc @silverwind
##

**Comment by silverwind** [comment]
Unless grunt tasks can take option arguments, that might be hard or impossible to in just grunt.

**Comment by silverwind** [comment]
We use big selector blocks like [this](https://github.com/StylishThemes/GitHub-Dark/blob/175a418426215dc00ef1793eb404b53e4c6fc631/github-dark.css#L272-L288). While it might not exactly be best practice, it's easier to do bulk changes this way. I'd love an option to wrap at a certain number of characters, which would keep the original ordering, so 

```css
.some-selector1, .some-selector2,
.some-selector3,
.some-selector5, .some-selector6, .some-selector4 {
  some-property: 1;
} 
```

turns into

```css
.some-selector1, .some-selector2, .some-selector3,
.some-selector5, .some-selector6, .some-selector4 {
  some-property: 1;
} 
```
