### ISSUE TITLE
Vendor prefixed background rule broke indetion for unprefixed rule

### ISSUE THREAD

**Issue by Yeti-or** [csscomb/csscomb.js#412]
```css
.b-autocomplete-item__loupe
{
    background: url('img.svg');
    background-size: 18px 19px;

    -webkit-background-position: 3px 9px;
    background-position: 3px 9px;
}
```
=>
```css
.b-autocomplete-item__loupe
{
    background: url('img.svg');
            background-position: 3px 9px;
    background-size: 18px 19px;

    -webkit-background-position: 3px 9px;
}
```
