### ISSUE TITLE
Doesn't trim spaces between transition properties

### ISSUE THREAD

**Issue by Yeti-or** [csscomb/csscomb.js#413]
Is it ok?

``` css
.page-layout__right
{transition: visibility 0s linear .15s,    transform .15s ease-out 10ms;
}
```

=>

``` css
.page-layout__right
{
    transition: visibility 0s linear .15s,    transform .15s ease-out 10ms;
}
```
##
