### ISSUE TITLE
Add config to enable space after clossing brace

### ISSUE THREAD

**Issue by najela** [csscomb/csscomb.js#414]
I would like to have a new line after each CSS declaration so that I have code like 

```css
.a {
 font: 10px;
}

.b{
 width: 30px;
}
```

Maybe a configuration such as `"space-after-clossing-brace": "\n",` will do

Thanks
