### ISSUE TITLE
PostCSS support

### ISSUE THREAD

**Issue by hudochenkov** [csscomb/csscomb.js#415]
[PostCSS](https://github.com/postcss/postcss) now is a big player at CSS processors market. More and more peoples start using it, and, I sure, many of them wants to use CSScomb with it. In many cases CSScomb in SCSS mode can process CSS with PostCSS plugins syntax, but sometimes it's fails and can't parse file.

PostCSS and CSScomb both going to their big releases. PostCSS 5.0 will [support custom parsers](https://github.com/postcss/postcss/issues/140). CSScomb 4.0, as I know, is heavy refactored. Maybe it's time to drop Gonzales PE and use PostCSS parsers for CSScomb?

PostCSS syntax can be very different because of used plugins and developers wants to have their source files organized.

This is example of PostCSS code, that current CSScomb (in Sublime Text) fails to process:

```css
.button {
    height: 40px;
    border: solid transparent;
    border-width: 2px;
    border-radius: calc(@height / 2);
    line-height: calc(@height - @border-width * 2);
}
```

Fails because of `@` in `calc()`. Used PostCSS plugins: [postcss-property-lookup](https://github.com/simonsmith/postcss-property-lookup) and [postcss-calc](https://github.com/postcss/postcss-calc).

More PostCSS-plugins syntaxes. [Mixins](https://github.com/postcss/postcss-mixins) are different from SCSS, for example, and there in no way to sort them now like we did it recently in [this PR](https://github.com/csscomb/csscomb.js/pull/392):

```css
@define-mixin icon $name {
    padding-left: 16px;
    &::after {
        content: "";
        background-url: url(/icons/$(name).png);
    }
}

.search {
    @mixin icon search;
}
```

Following code taken from [cssnext](http://cssnext.io/features/):

```css
/* custom properties & var() */

:root {
    --fontSize: 1rem;
}
h1 {
    font-size: calc(var(--fontSize) * 2);
}

/* custom media queries */

@custom-media --small-viewport (max-width: 30em);

@media (--small-viewport) {
    /* styles for small viewport */
}

/* media queries ranges */

Allows to replace min-/max- with <= & >= (syntax easier to read)

@media (width >= 500px) and (width <= 1200px) {
    /* your styles */
}

/* or coupled with custom media queries */

@custom-media --only-medium-screen (width >= 500px) and (width <= 1200px);

@media (--only-medium-screen) {
    /* your styles */
}
```

What you think about it, @tonyganch and @ai?

**Comment by ai** [comment]
We just dicussed it yesterday.

the current problem: PostCSS 5.0 has only CSS and SCSS parsers. In next month I have no plan to start Sass, Less and Stylus parsers.

ut I will write good docs about writing a parsers ;).

**Comment by isqua** [comment]
I’m interesting in CSScomb :heart: PostCSS. The file I have (I use postcss-nested):
```less
.header
{
    color: #fff;
    background-color: $darkGray;

    .wrapper {
        display: flex;
        flex-direction: column;

        @media (--tablet)
        {
            flex-direction: row;
        }
    }
}
```
and the error I get at csscombing:
```
Please check the validity of the block starting from line #6

4 |     background-color: $darkGray;
6*|     .wrapper {
7 |         display: flex;
8 |         flex-direction: column;
```
