### ISSUE TITLE
Bad Sorting in Nested Properties (background properties)

### ISSUE THREAD

**Issue by in-in** [csscomb/csscomb.js#416]
I use grunt-csscomb (3.0.1) and default yandex.json config. 
After csscomb background properties look too bad at the same time font properties keeps their sort order.

```scss
//before

.box {
  width: 400px;
  height: 200px;

  background: {
    color: gray;
    image: url(http://lorempixel.com/400/200/);
    repeat: no-repeat;
    position: center center;
  }

  font: {
    family: sans-serif;
    size: 1.5em;
    weight: 900;
  }
}

//after

.box {
  width: 400px;
  height: 200px;

  background: {
    position: center center;

    color: gray;

    image: url(http://lorempixel.com/400/200/);
    repeat: no-repeat;
  }

  font: {
    family: sans-serif;
    size: 1.5em;
    weight: 900;
  }
}
```
