### ISSUE TITLE
Question - new line for nested selectors (SCSS)

### ISSUE THREAD

**Issue by testerr123** [csscomb/csscomb.js#417]
Hi, how can I set from:

```scss
.test {
  width: 100%;
  color: #777;
  background-color: #fff;
  &:hover {
    background-color: #eee;
  }
  @media (min-width: 768px) {
    width: 50%;
  }
} 
```

to:

```scss
.test {
  width: 100%;
  color: #777;
  background-color: #fff;

  &:hover {
    background-color: #eee;
  }

  @media (min-width: 768px) {
    width: 50%;
  }
} 
```
