### ISSUE TITLE
$extend should have its own unique support

### ISSUE THREAD

**Issue by stowball** [csscomb/csscomb.js#419]
The docs state that you can use "`$include` — for included mixins (e.g. `@include` ... and `@extend` ...)", however, `$extend` should get its own unique support, as the preferred way for many Sass developers is to write their rulesets like this:

```scss
.foo {
  @extend %bar;

  normal: property;

  @include baz {
    another: property;
  }
}
```

This allows for the clear separation of:

1. This thing extends from another thing
2. I will then override any of the thing's extended properties with new ones
3. And then include any mixins specific to this thing.

Currently, adding `$include` in to the sort order lumps `@extend`s with it, thus breaking the visual flow of overriding properties.
