### ISSUE TITLE
block-indent is wrongly affecting closing brace

### ISSUE THREAD

**Issue by vitorgalvao** [csscomb/csscomb.js#424]
Given this CSS:

``` css
.first-property {
  position: fixed;
  top: 0;
}

.second-property { position: fixed; }
```

If the only CSSComb option we have is `"block-indent": 2`, the result will be:

``` css
.first-property {
  position: fixed;
  top: 0;
  }

.second-property { position: fixed; }
```

Suffice it to say, this is wrong. `}` should have been left alone, just like `.first-property {` was. After all, it is not part of the block itself.

“Why not just set `"space-before-closing-brace": "\n"` as well, then?” Because that will give us:

``` css
.first-property {
  position: fixed;
  top: 0;
}

.second-property { position: fixed;
}
```

And that is wrong as well. The goal here is to arrive at the first code example. From their names, `block-indent` is the misbehaving property.
##

**Comment by jonnymaceachern** [comment]
+1

**Comment by benlinton** [comment]
+1

**Comment by wallyzielinski** [comment]
+1. In my case, setting `"space-before-closing-brace": "\n"` still produces the undesired result of leaving the last closing brace indented.Would love to at least have an option for this added.

**Comment by sodatea** [comment]
What about the following configuration?
```JSON
{
  "space-after-opening-brace": "\n",
  "space-before-closing-brace": "\n",
  "block-indent": 2
}
```

The result is:
```css
.first-property {
  position: fixed;
  top: 0;
}

.second-property {
  position: fixed;
}
```
Is that acceptable?

I do agree with you that the `block-indent` option is misbehaving. But from @tonyganch's test files, I think that's exactly what he intends this rule to do… Changing that behavior would result in a breaking change for users.
Personally I'd like to do that in the v4 release (which won't come too soon…).

@tonyganch, what do you think?

**Comment by vitorgalvao** [comment]
@sodatea In what concerns my original post, that wouldn’t be acceptable. The goal was to arrive at the first code block (i.e. It would remain unchanged). Three lines for something that I’ve specifically set as one is also an issue.

[Having said that](http://youtu.be/ENHVQ2gslp8), I have since stopped using CSSComb, so I don’t really care either way. I keep the issue open simply because other people also expressed desire for the feature, so the desired outcome should be shifted for what they envision, not necessarily my top post.

**Comment by benlinton** [comment]
@sodatea Your fix works great for me.  Thanks.

With that being said, I do feel that the current behavior should be a bug rather than a feature.  Thanks again!

**Comment by achoukah** [comment]
@sodatea - That did the job beautifully for me..

```css
.second-property {
  position: fixed;
}
```

just looks nicer to me than:

```css
.second-property { position: fixed; }
```
