### ISSUE TITLE
Comment placement

### ISSUE THREAD

**Issue by clessg** [csscomb/csscomb.js#429]
Is there a way to have commented-out declarations be automatically reordered?

```css
.content {
  font-size: 18px;
  
  width: 1000px;
  margin: 10px;

  border: 1px solid #000;

  /* width: 200px; */
  background: #fff;
}
```

Current result:

```css
.content
{
    font-size: 18px;

    width: 1000px;
    margin: 10px;

    border: 1px solid #000;
    /* width: 200px; */
    background: #fff;
}

```

Failing that, might it be possible to make CSSComb not touch comments? For example, this:

```css
.content {
  font-size: 18px;

  /* This is pretty. */
  background: salmon;
}
```

gets converted into

```css
.content
{
    font-size: 18px;
    /* This is pretty. */

    background: salmon;
}
```

And I would like to have the comment kept in the same position that it was before.
