### ISSUE TITLE
Feature: Support newlines in space-after-opening-brace/space-before-closing-brace

### ISSUE THREAD

**Issue by MichielDeMey** [csscomb/csscomb.js#459]
Our current SCSS styleguide requires a newline after each `{` and `}`.

Like so:
```scss
.my-class {

  height: 100px;

  &.active {

    background: red;
    color: white;

  }

}
```

I tried setting multiple newline statements in the `space-after-opening-brace` option but that doesn't seem to work and only ever creates 1 newline.

My current (non-working) config:
```json
{
  "sort-order-fallback": "abc",
  "sort-order": ["..."],
  "space-after-opening-brace": "\n\n\r",
  "space-before-closing-brace": "\n\n\r",
  "rule-delimiter": "\n\n"
}
```

This outputs:

```scss
.my-class {
  height: 100px;

  &.active {
    color: red;
  }
}
```

Is this something that can be easily added?
The new `rule-delimiter` options seems to support multiple `\n` escape sequences, but not the others.
