### ISSUE TITLE
CSS custom properties (aka variables)

### ISSUE THREAD

**Issue by jhnns** [csscomb/csscomb.js#460]
First of all: Thanks for this awesome tool. I use it every day :+1: 

Is there a way to specify where to put all [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables)? For instance, I would like to put all custom properties at the end of the property list:

``` css
.button {
    height: 2rem;
    --button-background-color: hotpink;
    padding: 0.2rem;
}
```

should be reformatted like

``` css
.button {
    height: 2rem;
    padding: 0.2rem;
    --button-background-color: hotpink;
}
```
##
