### ISSUE TITLE
SCSS Sort Order

### ISSUE THREAD

**Issue by spAnser** [csscomb/csscomb.js#462]
Ran [import.css](https://github.com/csscomb/csscomb.js/blob/master/test/options/sort-order-scss/import.scss) through [csscomb.com/onlin](http://csscomb.com/online) and expected [import.expected.scss](https://github.com/csscomb/csscomb.js/blob/master/test/options/sort-order-scss/import.expected.scss) instead I got:
```
div
{
    color: tomato; @import 'foo.css';
}
```

Seeing similar issue with ```@include``` and ```@extend```

Noticed this bug using plugins for atom that rely on this library.

**Comment by octoxan** [comment]
Yeah my csscomb in Atom is pretty much useless. I can't use it on any of my .scss files without it ruining my code.

I have things set up like...

```css
div {
    display: none;
}
@include bp(min-width, $bp-small+1) {
    div {
        display: block;
    }
}
@include bp(min-width, $bp-medium+1) {
    div {
       display: inline-block;
    }
}
```
running csscomb turns my file into...

```css
@include bp(min-width, $bp-small+1) {
    div {
        display: block;
    }
}
@include bp(min-width, $bp-medium+1) {
    div {
       display: inline-block;
    }
}
div {
    display: none;
}
```

Which obviously is not good lol.
