### ISSUE TITLE
Rule: Convert pseudo-element colons

### ISSUE THREAD

**Issue by rugk** [csscomb/csscomb.js#470]
To fullfill [this rule by sass-lint](https://github.com/sasstools/sass-lint/blob/master/docs/rules/pseudo-element.md) a rule in csscomb would be useful, which can convert the colons of pseudo-elements to two or one ones.

E.g.

``` css
.popup:before {
  content: "Hello?"
}
```

could be converted to

``` css
.popup::before {
  content: "Hello?"
}
```

or vice versa...
##
