### ISSUE TITLE
Support for Polymer CSS mixins

### ISSUE THREAD

**Issue by JosefJezek** [csscomb/csscomb.js#480]
https://www.polymer-project.org/1.0/docs/devguide/styling#custom-css-mixins

``` css
.Tooltip {
        --paper-tooltip: {
          font-size: 16px;
        }
      }
```

```
Please check the validity of the block starting from line #2

1 | .Tooltip {
2*|         --paper-tooltip: {
3 |           font-size: 16px;
4 |         }

Gonzales PE version: 3.0.0-28
Syntax: css
```

Please ;-)
##

**Comment by tonyganch** [comment]
@JosefJezek, I will appreciate a PR to parser since it should be implemented there first: https://github.com/tonyganch/gonzales-pe

**Comment by JosefJezek** [comment]
How to set config for `@apply` mixins on top rules?

```css
.Button--navigation {
        @apply(--layout-vertical);
        @apply(--layout-center-center);
        
        height: var(--header-toolbar-height);
        padding: 0;
}
```

After csscomb

```css
.Button--navigation {
        height: var(--header-toolbar-height);
        padding: 0;

        @apply(--layout-vertical);
        @apply(--layout-center-center);
```
