### ISSUE TITLE
Unspecified error in mixn processing

### ISSUE THREAD

**Issue by Melmoth-the-Wanderer** [csscomb/csscomb.js#490]
Hello.

I'm using [CSSComb for VSCode](https://github.com/mrmlnc/vscode-csscomb). I've posted [this issue](https://github.com/mrmlnc/vscode-csscomb/issues/29) out there and have been redirected here with comment `it's CSSComb bug with parsing`. The problem is as folows:

I have the following `mixins.scss` file defined:

``` scss
@mixin floating-element() {
    border: 1px solid #d4d4d4;
    box-shadow: 0 0 20px -10px #000000;
}

@mixin get-subtable-colour($number) {
    $index: ($number % length($random-colours)) + 1;
    border-left: 2px solid unquote(nth($random-colours, $index));
}
```

when I run the `CSSComb` command on this particular file I'm getting the following error in VSCode console:

```
Parsing error: Please check the validity of the block starting from line #13



Gonzales PE version: 3.0.0-28
Syntax: scss
```

Please note, the file is 9 lines long, and the error message says `starting from line #13`.

Regards,
MP
##
