### ISSUE TITLE
sass: cannot assign & to a var

### ISSUE THREAD

**Issue by fly1ted** [csscomb/csscomb.js#494]
The problem is discussed in Glavin001/atom-beautify#1376

**Comment by jdalton** [comment]
@tonyganch 

Is this valid sass syntax. I see that gpe will parse it as scss:
```scss
.foo{
  $_: &;
  
  &--bar{
    & #{$_}-baz{
      text-align:center;
    }
  }
}
```
