### ISSUE TITLE
@extend, @include sort order

### ISSUE THREAD

**Issue by egor-xyz** [csscomb/csscomb.js#496]
How to put @extend first and @include latest?

```scss
.shop-modal-1 {
  @extend .shop-modal;
  max-width: 90%;
  @include max-width($shop-modal__step1) {
    max-width: 300px;
  }
}
```
