### ISSUE TITLE
Sort-order of @apply mixins

### ISSUE THREAD

**Issue by JosefJezek** [csscomb/csscomb.js#500]
How to set `sort-order` in config for `@apply` mixins on top rules?

``` css
.Button--navigation {
        @apply(--layout-vertical);
        @apply(--layout-center-center);

        height: var(--header-toolbar-height);
        padding: 0;
}
```

After csscomb

``` css
.Button--navigation {
        height: var(--header-toolbar-height);
        padding: 0;

        @apply(--layout-vertical);
        @apply(--layout-center-center);
}
```
