### ISSUE TITLE
Sass sorting by mixins

### ISSUE THREAD

**Issue by AxelBaron** [csscomb/csscomb.js#532]
Hello, 
I post new issue requested by @aiboy on #356. I use csscomb v.4.2.0.
I can't sort mixins in the order I want. For exemple, I have this scss file :  
```
body {
  display: block;
  @include clearfix();
  @include font-size(12px);
}
```

And I have this sort-order configuration in my .csscomb.json :  
```
"sort-order": [
    [
      "$include clearfix",
      "display",
      "$include size"
    ]
  ]
```

So what I want is have `@include clearfix();` before `display:block` propriety, and `@include font-size(12px);` after `display:block` propriety.

But when I run csscomb, my scss file look like this : 
```
body {
  display: block;

  @include clearfix();
  @include font-size(12px);
}
```

All @ include proprieties are group toghter at the end of the file. It's not that I want :/
There is a way to sort order mixin by name with csscomb ?

Thank for your time :)

**Comment by Tralgar** [comment]
That's a great idea, i need it too !
Btw, you could implement the difference between @include and @extend for example.
If i want a scss like this :

```scss
    &_bar {
      @extend .foo;
      color: red;
      width: 100%;
      @include breakpoint(medium) {
           width: 90%;
       }
       @include breakpoint(large) {
           width: 80%;
       }
    }
```

And if possible, i would sort the includes by type (small, medium and large). 
I think that's not really tricky to do no ? 😄 

Thanks !
