### ISSUE TITLE
lesscss loop handle issue

### ISSUE THREAD

**Issue by septs** [csscomb/csscomb.js#533]
valid less code

```less
.form-group.color .btn {
  .loop();
  .loop(@index:1) when (@index =< length(@player-score-overall-colors)) {
    @item: extract(@player-score-overall-colors, @index);
    @name: e(extract(@item, 1));
    @borderColor: extract(@item, 2);
    @backgroundColor: extract(@item, 3);
    .loop(@index + 1);

    &.@{name} {
      background: @backgroundColor;
      border-color: @borderColor;
      color: #fff;
      text-shadow: 0 -1px 0 fade(#000, 25%);
      font-weight: bold;
    }
  }
}
```

error info:
```
(node:86553) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Parsing error: pages/player/filter/header.less
Please check validity of the block starting from line #26
CSScomb Core version: 4.2.0

24 |   .form-group.color .btn {
25 |     .loop();
26*|     .loop(@index:1) when (@index =< length(@player-score-overall-colors)) {
27 |       @item: extract(@player-score-overall-colors, @index);
28 |       @name: e(extract(@item, 1));

Syntax: less
Gonzales PE version: 3.4.7
(node:86553) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^C
```
