### ISSUE TITLE
SASS inline comments breaks sort ordering (and thus the SASS itself)

### ISSUE THREAD

**Issue by dominique-mueller** [csscomb/csscomb.js#535]
When using SASS comments inline, for instance next to a declaration, the whole formatting breaks apart.

**Example:**
``` scss
.input {
  font-family: inherit; // My awesome comment
  line-height: 20px;
}
```
The code above gets transformed into:
``` scss
.input {
  font-family: inherit; // My awesome comment  line-height: 20px;
}
```

Sometimes, it even destroys the new line formatting, for example:
``` scss
.input {
  font-family: inherit; // My awesome comment
  line-height: 20px; // My other comment
}
```
The code above gets transformed into:
``` scss
.input { font-family: inherit; // My awesome comment
  line-height: 20px; // My other comment
}
```

Seems that CSS-style comments (`/* ... */` instead of `// ...`) work fine though.
