### ISSUE TITLE
LESS: Parsing error with contiguous ampersands (&)

### ISSUE THREAD

**Issue by parkerbossier** [csscomb/csscomb.js#548]
**Input**

```less
.Thing {
	&-left {
		color: red;
	}

	&-left&-otherLeft {
		color: blue;
	}
}
```

**Output**

```
Parsing error: myfile.less
Please check validity of the block starting from line #6
CSScomb Core version: 4.2.0

4 | 	}
6*| 	&-left&-otherLeft {
7 | 		color: blue;
8 | 	}

Syntax: less
Gonzales PE version: 3.4.7
```

**Note**

Adding a space between `&-left` and `&-otherLeft` in the `&-left&-otherLeft` line works (but is obviously a different selector).
