### ISSUE TITLE
@keyframes multiple values in sublime plugin fails

### ISSUE THREAD

**Issue by Federico-G** [csscomb/csscomb.js#568]
In sublime plugin, @keyframes fails if you use multiple values. In the online version, it works fine

Plugin version: 4.2.0

Example:
```css
@keyframes backSlideIn {
  0%, 25% { /* ERROR */
    opacity: .5;
    transform: translateZ(-400px) translateX(200%);
  }
/* ... */
}
```
