### ISSUE TITLE
Issue with eof-newline

### ISSUE THREAD

**Issue by line47** [csscomb/csscomb.js#572]
I'd expect the results of `"eof-newline": true` to put a newline after every https://github.com/csscomb/csscomb.js/blob/dev/doc/options.md#eof-newline

However that is not happening when I run CSS Comb on an entire file.

Here is my config:
```json
{
    "exclude": [
        ".git/**",
        "node_modules/**",
        "bower_components/**"
    ],
    "always-semicolon": true,
    "block-indent": "  ",
    "color-case": "lower",
    "color-shorthand": true,
    "element-case": "lower",
    "include": true,
    "eof-newline": true,
    "leading-zero": false,
    "quotes": "single",
    "remove-empty-rulesets": true,
    "space-after-colon": " ",
    "space-after-combinator": " ",
    "space-after-opening-brace": "\n",
    "space-after-selector-delimiter": "\n",
    "space-around-operator": " ",
    "space-before-closing-brace": "\n",
    "space-before-colon": "",
    "space-before-combinator": " ",
    "space-before-opening-brace": " ",
    "space-before-selector-delimiter": "",
    "space-between-declarations": "\n",
    "strip-spaces": true,
    "tab-size": true,
    "unitless-zero": true,
    "vendor-prefix-align": true,
    "sort-order": [ "..." ],
    "sort-order-fallback": "abc"
  }
```

Here is my SCSS before running CSS Comb:
```scss
.label-success {
  background-color: $label-success-bg-color;
}
.label-danger {
  background-color: $label-danger-bg-color;
}
.label-warning {
  background-color: $label-warning-bg-color;
}
```

Here is my SCSS **after** running CSS Comb: (no change 😢 )
```scss
.label-success {
  background-color: $label-success-bg-color;
}
.label-danger {
  background-color: $label-danger-bg-color;
}
.label-warning {
  background-color: $label-warning-bg-color;
}
```

**What am I missing here?**
