### ISSUE TITLE
lines-between-rulesets move the comment of previous rule

### ISSUE THREAD

**Issue by robsonsobral** [csscomb/csscomb.js#577]
The rule `lines-between-rulesets` moves the comment of previous rule.

before:

```css
	border-radius: $line-height * 1em; // sass-lint:disable-line property-units

	&::before {
		vertical-align: text-bottom;

		content: '\25a0\a0';
	}
```

After:

```css
	border-radius: $line-height * 1em;

	// sass-lint:disable-line property-units

	&::before {
		vertical-align: text-bottom;

		content: '\25a0\a0';
	}
```
