### ISSUE TITLE
SCSS + concatination fails

### ISSUE THREAD

**Issue by wesselbaum** [csscomb/csscomb.js#600]
My following SCSS rule
``` scss
.mejs-overlay-button {
  background-image: url($icon-mediaelementjs + 'play_custom.svg');
}
```
results in
``` scss
.mejs-overlay-button {
  background-image: url($icon-mediaelementjs ) 'play_custom.svg';;
}
```
which is not what it supossed to result.

Am I doing something wrong?
