### ISSUE TITLE
Can spaces before first selector be removed?

### ISSUE THREAD

**Issue by BartolomeSintes** [csscomb/csscomb.js#621]
CSSComb configuration in Visual Studio Code:
```json
"csscomb.preset": {
    "block-indent": "    ",
    "space-after-opening-brace": "\n",
    "space-before-closing-brace": "\n"
}
```
Initial CSS code (notice the blank spaces before selectors):
```css
    h1 { color: black; }
    h2 { color: black; }
```
Obtained result (blank spaces before the first selector are not removed):
```css
    h1 {
    color: black;
}
h2 {
    color: black;
}
```
Expected result (both blank spaces before first and second selector removed)
```css
h1 {
    color: black;
}
h2 {
    color: black;
}
```
Is it a CSSComb bug? Is there a CSSComb configuration option that removes the spaces before the first selector?
Thanking you in advance,
