### ISSUE TITLE
Extra semicolon after sorting properties

### ISSUE THREAD

**Issue by BartolomeSintes** [csscomb/csscomb.js#622]
CSSComb configuration in Visual Studio Code:
```json
"csscomb.preset": {
    "always-semicolon": true,
    "sort-order": [ "text-align", "text-transform" ]
}
```
Initial CSS code (notice missing semicolon after second property):
```css
h1 {
    text-transform: uppercase;
    text-align: center
}
```
Obtained result (there are two semicolons after first property):
```css
h1 {
    text-align: center;;
    text-transform: uppercase;
}
```
Expected result (one semicolon after both properties)
```css
h1 {
    text-align: center;
    text-transform: uppercase;
}
```
Is it a known CSSComb bug? 
Thanking you in advance,
