### ISSUE TITLE
space-after-selector-delimiter : Indentation inside @media with multiple selectors

### ISSUE THREAD

**Issue by julien-** [csscomb/csscomb.js#653]
# My config : 
```
{
  "space-after-selector-delimiter": "\n",
  "color-case": "lower"
}
```

I am using [gulp-csscomb library](https://www.npmjs.com/package/gulp-csscomb) , here is [my Gulp repo](https://github.com/julien-/gulp_browsersync) if you want to test
# Before :
_You can test it as .SCSS code_
```css
@media only screen and (max-width: 767px) {
  #sel1,
  #sel2 {
    background: red;
  }
}

#sel3 {
  padding: 5px;
}
```

# After :
```css
@media only screen and (max-width: 767px) {
  #sel1,
#sel2 {
    background: red;
  }
}
#sel3 {
  padding: 5px;
}

```

# Wanted
I want the same than in **Before**, so :

1. Fix issue of "space-after-selector-delimiter" inside @media block
2. Fix issue of space after @media block (as you can see, there is no new line)
