### ISSUE TITLE
Option to align property-value parts

### ISSUE THREAD

**Issue by kizu** [csscomb/csscomb.js#82]
Similar to #17, but for aligning all the property-value parts. For example, `property-value-align`.

I guess, when this option is `true`, we should align things only inside their “groups”. I don't think that overall aligning among all the properties inside a declaration makes any sense, and adding different values to make all variants possible would just complicate things.

So, `false` value should remove all the aligning if it present, and `true` should align the values inside groups, like this:

``` CSS
/* before */
p {
    margin: 0;
    padding: 0;

    border: 0;
    background: none;
}

/* after */
p {
    margin:  0;
    padding: 0;

    border:     0;
    background: none;
}
```

It's obvious, that this option should run after the `sort-order` one, so the right groups would be aligned.

While I think those two (`true` and `false`) values would be enough, there could be different possible variants (including overall aligning), like

``` CSS
p {
    margin : 0;
    padding: 0;

    border    : 0;
    background: none;
}

p {
     margin: 0;
    padding: 0;

        border: 0;
    background: none;
}

p {
    margin:     0;
    padding:    0;

    border:     0;
    background: none;
}

```

etc. Dunno if someone would need those, but we could add different string keywords to make those possible.
