### ISSUE TITLE
Strange bug in sort-order

### ISSUE THREAD

**Issue by kizu** [csscomb/csscomb.js#94]
When I use the `0.1.0` csscomb on this CSS (with [those](https://raw.github.com/csscomb/csscomb.js/master/.csscomb.json) settings):

``` CSS
.test
{
    position: absolute;
    top: -1px;
    right: -1px;
    bottom: -1px;
    left: -1px;

    border: 1px solid transparent;
    border-color: rgba(0,0,0,0.38) rgba(0,0,0,0.27) rgba(0,0,0,0.16);

    background: -webkit-linear-gradient(#fff, #fff);
    background: linear-gradient(#fff, #fff);
    background-clip: padding-box;
    background-size: 16px 16px;

    -webkit-appearance: textfield;
}
```

I get this result:

``` CSS
.test
{
    position: absolute;
    -webkit-appearance: textfield;
    right: -1px;
    bottom: -1px;
    left: -1px;

    border: 1px solid transparent;

    top: -1px;

    background: -webkit-linear-gradient(#fff, #fff);
    background: linear-gradient(#fff, #fff);
    background-clip: padding-box;
    background-size: 16px 16px;
    border-color: rgba(0,0,0,.38) rgba(0,0,0,.27) rgba(0,0,0,.16);
}
```

You can see how the `-webkit-appearance`, `top` and `border-color` are placed.
