### ISSUE TITLE
bug: vendor-align-prefix

### ISSUE THREAD

**Issue by mishanga** [csscomb/csscomb.js#98]
before/after:

``` css
 .serp-block__head_animation_yes
 {
     -webkit-transition: -webkit-transform 150ms linear;
-            transition:         transform 150ms linear;
+            transition: transform 150ms linear;
 }
```
